Lazy loading features
vpusher/paper-tree pull request #3
Opened 2017-02-19 14:40 UTC by platoscave

This branch contains features that facilitate lazy loading
Including in paper-tree-node:

- a new `toggle-children` event fired from toggleChildren
- a new class selector for the loading icon: `.node-preicon.loading:before` 
- the addition of  `src$="[[data.src]]"` to the iron-icon (not related to lazy loading)

New files:

- loading.svg: animated loading icon
- lazyload-demo: a custom element that demonstrates lazy loading

Chris

2017-02-20 15:56 UTC, vpusher reviewed
@platoscave In my mind the component should not know about the lazy stuff. It is only dumb UI. All we need to provide is utils and events so it can implemented by the end-developer easily.

Consequently, let's only keep a `toggle` event on `<paper-tree-node>`, that will bubble up to the top `<paper-tree>` for listening purpose. So no CSS selectors specific to lazy loading, no embbeded svg.

Icon could be updated with something like: 

```html
<paper-tree on-toggle-children="toggleChildren"</paper-tree>
[...]
function toggleChildren(e) {
    var node = e.detail;
    node.set('data.icon', 'loading');
}
```

2017-02-20 16:09 UTC, vpusher requested changes

2017-02-20 16:09 UTC, vpusher commented on demo/lazyload-demo.html
> +
Could you provide something much more simpler and shorter ? This would act as a sample. It have to be understood in seconds. We only need to listen 'toggle' event and some lazy data fetcher (a few lines)

2017-02-20 16:09 UTC, vpusher commented on loading.svg
> +<svg id="loading" width='24px' height='24px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="uil-default"><rect x="0" y="0" width="100" height="100" fil
As explained, lazyness is not part of the component. Consider remove this image.

2017-02-20 16:09 UTC, vpusher commented on paper-tree-node.html
> +
Same here. Remove that block.

2017-02-20 16:09 UTC, vpusher commented on paper-tree-node.html
> +         * @event toggle-children
I would go for a `toggle` event name.

2017-02-20 16:09 UTC, vpusher commented on paper-tree-node.html
> +            if(change && change.base && change.base.loading) return 'node-preicon loading';
Remove this also.

2017-02-20 16:09 UTC, vpusher commented on paper-tree-node.html
> +            this.fire("toggle-children", this);
`this.fire('toggle', this);`

2017-02-21 03:09 UTC, platoscave commented
@vpusher 
The problem with this approach is, it's not the icon we want to (un-)set to loading, it's the preicon.
This would involve updating the class of the node from the 'toggle' event in the host. We would also have to inject the loading class from the host with one of those weird '>' notations. Any thoughts on how to achieve this?
While I agree with your philosophy, I don't necessarily agree that adding a loading state detracts from "dumbness". `open` can be thought of as having four states: expanded, collapsed, loading, none. This will work in any world. 
Lazy loading is especially important in enterprise applications where we're dealing with large amounts of data: "Give me all employees beginning with 'A'". This is where paper-tree will come into its own. It makes sense to provide these features out-of-the-box. 
Another approach might be to change `open` from Boolean to something that can hold four states.

2017-02-21 08:40 UTC, platoscave commented
@vpusher 
The problem with this approach is, it's not the icon that we want to (un-)set to loading, it's the preicon.
This would involve setting the node class from the `toggle` event in the host. We would also have to inject the `loading` class into the child with one of those weird '>' notations. Any thoughts on how to achieve this?

While I agree with your philosophy I don't necessarily a agree that adding a loading icon detracts from "dumbness". 'open' can be thought of as having four states: expanded, collapsed, loading and none, each with their own representation in the UI.

Lazy loading is an important feature for trees, especially in enterprise environments: "Give me all employees beginning with 'A'". This is where paper-tree will come into its own. It makes sense to support this out-of-the-box.

2017-02-21 09:39 UTC, platoscave commented on demo/lazyload-demo.html
> +
I'll have a go at this.

2017-02-21 10:30 UTC, vpusher commented
I know how important it is to lazy load data, and how much you need it in some case. The thing is some will want to update the pre-icon, the others will want to update the icon and perhaps some others will want a loading text message (or both, or the three). That is to say the way the loading feedback is rendered is under the end developer responsibility. I don't want to take any opinion on this. This is a view that is bound to a model and it provides some hooks/events to implement you own logic.

To resume, to solve your issue the component needs the followings openings/hooks:

[x] know when children are toggled: a `toggle` event is needed.
[ ] be able to change **pre-icon**: a mixin would be a good answer for that.
[x] be able to change **icon**: you can actually do it editing the node's `data.icon`
[x] be able to change **text**: you can actually do it editing the node's `data.name`

2017-02-21 14:10 UTC, vpusher commented on demo/lazyload-demo.html
> +
could you add it as a dom bind (instead of a component) in the demo page. and fix the former demos BTW  😅

2017-02-22 15:36 UTC, platoscave commented
@vpusher 
I've adopted your recommendations in the latest push. 
In order to enable changing the pre-icon I've add the --loading-icon-theme that can serve as a mixin to paper-tree-node.

The lazyload-demo is now much simpler and works fine, all except for applying the 'loading' class to the pre-icon span. The 'loading' class needs to be applied shortly after the node is created due to a data update. These spans are really hard to find. I thought about searching the dom tree but this is generally discouraged because "It requires the consumer to be aware about element's internals. Web component should only be used with properties/attributes and events".

What would be a good way to get access the pre-icon <span> so that we can modify it's class?

2017-02-24 15:40 UTC, vpusher commented
@platoscave what about my last commit ? does it fit your needs ?

2017-02-27 23:16 UTC, platoscave commented
We have to add `target.loaded = true;` to the demo's, Apart from that, that it works like a charm.

I'm also testing `--paper-tree-icon-theme`. It turns out that iron-icon doen't provide much in the way of mixins to do something with the icon, other than size and color.
I found, what I think might be a better way to modify the icon:
```
setNodeIcon: function (node, icon) {
     var ironIcon = node.$$('iron-icon');
     ironIcon.set('src', icon);
 },
```
The only problem here is the issue which I mentioned earlier: [iron-icon `icon` takes precedence over `src` contrary to docs #78](https://github.com/PolymerElements/iron-icon/issues/78). I'd have to hack my way around this as long as it hasn't been resolved. If this is an acceptable way of working we might not need `--paper-tree-icon-theme`.

Note: I had to add `src/` to `background:url(\'src/loading.svg\');\` in `setLoadingState`. I'm not sure if something similar is needed in your demo's, as I'm not running the code directly, but rather from my custom element.

How does one go about running the demo's, given that there is no bower-components context?

2017-02-28 09:22 UTC, vpusher commented
@platoscave do you run it with `polymer serve` ?

2017-03-01 02:27 UTC, benbenbenbenbenben commented
In my opinion the solution here is overly complicated. You can lazy render simply by using dom-if in a template on children. If a node isn't visible it isn't rendered (yet).

#4

2017-03-01 08:59 UTC, vpusher commented
@benbenbenbenbenben here we are mostly dealing with customizing the UI through openings/hooks such as events and mixins (to fit the use case of @platoscave). Data lazy loading is totally in charged of the end developer. That's the first point. The second point is about lazy render the tree, and that is the purpose of your PR. Tank you for that, I will consider it, merge it and then release a new version of the component with those 2 enhancements (PRs).

2017-03-01 11:38 UTC, vpusher commented
@platoscave I am merging this one. Most of your use cases are covered now, and the current implementation seems generic enough to me. Please address a new PR for the icon `src` issue if you really need it.

2017-03-01 11:38 UTC, merged

2017-03-03 16:24 UTC, benbenbenbenbenben commented
@vpusher okay thanks for this

2017-03-08 15:41 UTC, vpusher commented
@platoscave Released in [v1.0.3](/vpusher/paper-tree/releases/tag/v1.0.3)